"""
Django settings for hostel_manager project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# QUICK-START (development) — change SECRET_KEY & DEBUG for production
SECRET_KEY = 'django-insecure-o#*3#y8=_3i(py*gk16hwjb*cs&$41a10!1)fj_ycj0%*7!-7v'  # keep secret in prod
DEBUG = True
ALLOWED_HOSTS = []  # add hostnames/ip when deploying, e.g. ['yourdomain.com','127.0.0.1']


# Application definition
INSTALLED_APPS = [
    # default django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'malnad_hostel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hostel_manager.urls'

# Templates: include a project-level templates/ folder and app templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Add a project-level templates directory so you can place shared templates there
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # request processor is useful (login, path, etc.)
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # optionally you can add:
                # 'django.template.context_processors.debug',
                # 'django.template.context_processors.i18n',
                # 'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'hostel_manager.wsgi.application'


# Database (default sqlite for dev)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation (default)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'   # change to your timezone, e.g. 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# During development Django serves static files automatically when DEBUG=True.
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # where you store project-level static files
# For production, you will configure STATIC_ROOT and run collectstatic
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (user uploaded) — optional now but good to have
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Authentication redirects (simple defaults)
LOGIN_REDIRECT_URL = '/'       # where to go after login
LOGOUT_REDIRECT_URL = '/'      # where to go after logout
LOGIN_URL = '/accounts/login/' # used by @login_required (Django's built-in auth URLs)


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
